title: TMM_CfM
description: Transfer Matrix Method for Coding for Machines
theme: jekyll-theme-cayman

url: "https://sf219.github.io"
baseurl: "/TMM_CfM"

# Author info (for header/footer)
author:
  name: "Samuel Fernández-Menduiña"
  avatar: "/assets/img/avatar.png" # optional
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sf219/TMM_CfM"
    - label: "arXiv"
      icon: "fas fa-file-alt"
      url: "https://arxiv.org/abs/2504.02216"

# Navigation (top bar)
navigation:
  - title: "Home"
    url: /
  - title: "Paper"
    url: /paper/
  - title: "Notebooks"
    url: /notebooks/
  - title: "GitHub"
    url: https://github.com/sf219/TMM_CfM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Optional extras
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
